In [2]:
import numpy as np
import pandas as pd 
diamond = pd.read_csv("../Diamond Price Prediction.csv")
diamond

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [3]:
diamond.shape

(53940, 10)

In [4]:
diamond.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Carat(Weight of Daimond)  53940 non-null  float64
 1   Cut(Quality)              53940 non-null  str
 2   Color                     53940 non-null  str
 3   Clarity                   53940 non-null  str
 4   Depth                     53940 non-null  float64
 5   Table                     53940 non-null  float64
 6   Price(in US dollars)      53940 non-null  int64
 7   X(length)                 53940 non-null  float64
 8   Y(width)                  53940 non-null  float64
 9   Z(Depth)                  53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [5]:
diamond.head(5)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [6]:
diamond.isnull().sum()

Carat(Weight of Daimond)    0
Cut(Quality)                0
Color                       0
Clarity                     0
Depth                       0
Table                       0
Price(in US dollars)        0
X(length)                   0
Y(width)                    0
Z(Depth)                    0
dtype: int64

In [7]:
diamond.sample(20)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
51044,0.70,Premium,H,VS2,61.8,60.0,2330,5.68,5.71,3.52
15396,1.12,Ideal,E,SI2,61.6,56.0,6168,6.69,6.71,4.13
1954,0.91,Very Good,H,SI1,63.0,57.0,3087,6.10,6.19,3.87
3032,0.26,Very Good,H,VVS2,63.4,55.0,565,4.06,4.05,2.57
7177,1.01,Good,G,SI2,63.8,53.0,4185,6.41,6.31,4.06
9157,0.90,Very Good,G,VS1,62.3,60.0,4540,6.00,6.08,3.76
16204,1.21,Ideal,G,VS2,61.7,56.0,6478,6.85,6.83,4.22
18384,0.26,Ideal,F,VS1,62.4,53.0,618,4.11,4.13,2.57
51281,0.73,Very Good,F,SI1,63.5,56.0,2360,5.68,5.72,3.62
2358,0.71,Very Good,F,VS1,62.9,55.0,3175,5.68,5.71,3.58
53641,0.73,Very Good,D,SI2,60.4,59.0,2703,5.80,5.86,3.52
17124,1.04,Ideal,G,VS1,61.5,55.0,6831,6.54,6.55,4.02
26217,2.10,Premium,I,SI1,59.9,61.0,15615,8.34,8.26,4.97
7361,1.00,Good,D,SI2,61.5,63.0,4218,6.27,6.32,3.87
37618,0.23,Very Good,E,VVS1,58.8,61.0,485,3.98,4.01,2.35
38053,0.34,Fair,E,VVS1,54.0,56.0,1012,4.80,4.76,2.58
46456,0.54,Ideal,H,VVS1,61.9,54.0,1774,5.22,5.25,3.24
50121,0.54,Ideal,H,IF,60.3,55.0,2210,5.29,5.33,3.20
21813,1.18,Ideal,E,VS1,62.4,54.0,9886,6.79,6.74,4.22
31204,0.32,Premium,D,SI1,60.8,58.0,756,4.44,4.41,2.69

In [8]:
diamond.isnull().sum()

Carat(Weight of Daimond)    0
Cut(Quality)                0
Color                       0
Clarity                     0
Depth                       0
Table                       0
Price(in US dollars)        0
X(length)                   0
Y(width)                    0
Z(Depth)                    0
dtype: int64

In [9]:
(diamond.isnull().sum()/len(diamond))*100

Carat(Weight of Daimond)    0.0
Cut(Quality)                0.0
Color                       0.0
Clarity                     0.0
Depth                       0.0
Table                       0.0
Price(in US dollars)        0.0
X(length)                   0.0
Y(width)                    0.0
Z(Depth)                    0.0
dtype: float64

In [10]:
diamond.dropna(axis=1)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [11]:
diamond.drop_duplicates().sum()

Carat(Weight of Daimond)                                             42915.78
Cut(Quality)                IdealPremiumGoodPremiumGoodVery GoodVery GoodV...
Color                       EEEIJJIHEHJJFJEEIJJJIEHJJGIJDFFFEEDFEHDIIJDDHF...
Clarity                     SI2SI1VS1VS2SI2VVS2VVS1SI1VS2VS1SI1VS1SI1SI2SI...
Depth                                                               3321676.2
Table                                                               3090901.5
Price(in US dollars)                                                211575303
X(length)                                                           308304.95
Y(width)                                                            308489.94
Z(Depth)                                                            190361.56
dtype: object

In [12]:
diamond.drop_duplicates(inplace=True)

In [13]:
diamond

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [14]:
diamond.dtypes

Carat(Weight of Daimond)    float64
Cut(Quality)                    str
Color                           str
Clarity                         str
Depth                       float64
Table                       float64
Price(in US dollars)          int64
X(length)                   float64
Y(width)                    float64
Z(Depth)                    float64
dtype: object

In [15]:
diamond

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [16]:
diamond['Color'].unique()

<ArrowStringArray>
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Length: 7, dtype: str

In [17]:
diamond[['Table', 'Depth']].apply(pd.Series.value_counts)

      Table  Depth
43.0    1.0    2.0
44.0    1.0    1.0
49.0    2.0    NaN
50.0    2.0    NaN
50.1    1.0    NaN
...     ...    ...
73.6    NaN    1.0
76.0    1.0    NaN
78.2    NaN    1.0
79.0    1.0    1.0
95.0    1.0    NaN

[203 rows x 2 columns]

In [ ]:
diamond.columns = ['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']

for col in ['cut', 'color', 'clarity']:
    print(f"--- {col} Value Counts ---")
    print(diamond[col].value_counts(), "\n")

diamond.describe()git

--- cut Value Counts ---
cut
Ideal        21488
Premium      13748
Very Good    12069
Good          4891
Fair          1598
Name: count, dtype: int64

--- color Value Counts ---
color
G    11262
E     9776
F     9520
H     8272
D     6755
I     5407
J     2802
Name: count, dtype: int64

--- clarity Value Counts ---
clarity
SI1     13032
VS2     12229
SI2      9150
VS1      8156
VVS2     5056
VVS1     3647
IF       1784
I1        740
Name: count, dtype: int64

,carat,depth,table,price,x,y,z
count,53794.00000,53794.000000,53794.000000,53794.000000,53794.000000,53794.000000,53794.000000
mean,0.79778,61.748080,57.458109,3933.065082,5.731214,5.734653,3.538714
std,0.47339,1.429909,2.233679,3988.114460,1.120695,1.141209,0.705037
min,0.20000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.40000,61.000000,56.000000,951.000000,4.710000,4.720000,2.910000
50%,0.70000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.04000,62.500000,59.000000,5326.750000,6.540000,6.540000,4.030000
max,5.01000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000