In [87]:
import numpy as np
import pandas as pd 
diamond = pd.read_csv("../Diamond Price Prediction.csv")
diamond

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [88]:
diamond.shape

(53940, 10)

In [89]:
diamond.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Carat(Weight of Daimond)  53940 non-null  float64
 1   Cut(Quality)              53940 non-null  str
 2   Color                     53940 non-null  str
 3   Clarity                   53940 non-null  str
 4   Depth                     53940 non-null  float64
 5   Table                     53940 non-null  float64
 6   Price(in US dollars)      53940 non-null  int64
 7   X(length)                 53940 non-null  float64
 8   Y(width)                  53940 non-null  float64
 9   Z(Depth)                  53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.7 MB

In [90]:
diamond.head(5)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [91]:
diamond.isnull().sum()

Carat(Weight of Daimond)    0
Cut(Quality)                0
Color                       0
Clarity                     0
Depth                       0
Table                       0
Price(in US dollars)        0
X(length)                   0
Y(width)                    0
Z(Depth)                    0
dtype: int64

In [92]:
diamond.sample(20)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
8260,0.90,Very Good,F,SI1,61.4,58.0,4379,6.18,6.23,3.81
31506,0.34,Premium,G,VS2,61.0,58.0,765,4.49,4.46,2.73
45445,0.55,Ideal,D,VS2,61.6,57.0,1673,5.25,5.30,3.25
47053,0.71,Very Good,J,VS2,62.8,61.0,1821,5.63,5.71,3.56
3703,1.00,Ideal,E,SI2,62.9,56.0,3450,6.32,6.30,3.97
46069,0.46,Ideal,E,VVS2,62.6,55.0,1736,4.95,4.92,3.09
32396,0.31,Ideal,E,VVS2,61.3,55.0,791,4.35,4.39,2.68
7511,0.61,Ideal,D,VVS1,62.1,56.0,4241,5.43,5.46,3.38
34517,0.33,Ideal,G,VVS1,62.0,56.0,868,4.45,4.48,2.77
22628,1.68,Ideal,J,VS1,61.1,57.0,10681,7.64,7.70,4.69
8861,0.90,Very Good,E,VS2,63.3,59.0,4482,6.08,6.12,3.86
7267,1.03,Ideal,I,VS1,62.4,57.0,4199,6.48,6.40,4.02
7059,0.33,Premium,I,VVS2,61.0,58.0,579,4.42,4.46,2.71
32507,0.40,Very Good,E,SI2,63.1,57.0,798,4.72,4.70,2.97
25919,2.05,Premium,J,VS1,60.1,58.0,15067,8.25,8.19,4.94
35932,0.35,Premium,E,VS2,61.9,61.0,919,4.54,4.50,2.80
35457,0.49,Premium,J,SI2,59.8,59.0,900,5.14,5.12,3.07
45067,0.55,Very Good,H,VS1,61.0,56.0,1643,5.26,5.30,3.22
23171,2.01,Premium,J,SI1,60.3,56.0,11188,8.02,7.96,4.82
2500,0.71,Ideal,E,VS1,61.4,59.0,3198,5.71,5.75,3.52

In [93]:
diamond.isnull().sum()

Carat(Weight of Daimond)    0
Cut(Quality)                0
Color                       0
Clarity                     0
Depth                       0
Table                       0
Price(in US dollars)        0
X(length)                   0
Y(width)                    0
Z(Depth)                    0
dtype: int64

In [94]:
(diamond.isnull().sum()/len(diamond))*100

Carat(Weight of Daimond)    0.0
Cut(Quality)                0.0
Color                       0.0
Clarity                     0.0
Depth                       0.0
Table                       0.0
Price(in US dollars)        0.0
X(length)                   0.0
Y(width)                    0.0
Z(Depth)                    0.0
dtype: float64

In [95]:
diamond.dropna(axis=1)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [96]:
diamond.drop_duplicates().sum()

Carat(Weight of Daimond)                                             42915.78
Cut(Quality)                IdealPremiumGoodPremiumGoodVery GoodVery GoodV...
Color                       EEEIJJIHEHJJFJEEIJJJIEHJJGIJDFFFEEDFEHDIIJDDHF...
Clarity                     SI2SI1VS1VS2SI2VVS2VVS1SI1VS2VS1SI1VS1SI1SI2SI...
Depth                                                               3321676.2
Table                                                               3090901.5
Price(in US dollars)                                                211575303
X(length)                                                           308304.95
Y(width)                                                            308489.94
Z(Depth)                                                            190361.56
dtype: object

In [97]:
diamond.drop_duplicates(inplace=True)

In [98]:
diamond

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [99]:
diamond.dtypes

Carat(Weight of Daimond)    float64
Cut(Quality)                    str
Color                           str
Clarity                         str
Depth                       float64
Table                       float64
Price(in US dollars)          int64
X(length)                   float64
Y(width)                    float64
Z(Depth)                    float64
dtype: object

In [100]:
diamond

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [101]:
diamond['Color'].unique()

<ArrowStringArray>
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Length: 7, dtype: str

In [104]:
diamond[['Table', 'Depth']].apply(pd.Series.value_counts)

      Table  Depth
43.0    1.0    2.0
44.0    1.0    1.0
49.0    2.0    NaN
50.0    2.0    NaN
50.1    1.0    NaN
...     ...    ...
73.6    NaN    1.0
76.0    1.0    NaN
78.2    NaN    1.0
79.0    1.0    1.0
95.0    1.0    NaN

[203 rows x 2 columns]